# 172.29.0.94 telnet yanfan,baiteng123
# display interface brief
# display int Ethernet 0/0/0
proxy:
  config:
    local-port: 8023
    remote-ip: 172.29.0.94
  #  list:
  #    - local-port: 8022
  #      remote-ip: 192.168.38.128
  #      remote-port: 22

transfer:
  interface-regex: "(Eth-Trunk[0-9]+|Route-Aggregation[0-9]+|XGE[0-9]+/[0-9]+/[0-9]+/[0-9]+|Ethernet[0-9]+)"
  input-rate: 515256457452
  output-rate: 616156254723
  total: 160
logging:
  level:
    com.yunzhicloud.proxy: info
